Artifactory:
  server: melissayavuz.jfrog.io #change to your servername
  intName: artifactory_integration
  devRepo: workshop1-docker-local
  prodRepo: workshop-docker-prod-local
GitHub:
  path: emine1576/aws-eks-workshop #change to your github username
  gitProvider: github_integration
AWS:   
  intName: aws_integration
  eks: eks_integration
  region: us-west-2
app:
  dockerImageName: melissayavuz.jfrog.io/workshop-docker/eks-workshop-app #change to your servername .  
  dockerFileLocation: workshop-app
  buildName: eks-workshop-app
